[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions."delete-all-users"]
  external_node_modules = ["firebase-admin"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Functions-д зориулсан CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
